export const Products = [
  {
    id: "lego-city-fire-station",
    name: "LEGO City Fire Station",
    brand: "LEGO",
    price: 59.99,
    age: "6+",
    category: "building sets",
    description: "Fire station playset with fire engine and firefighter minifigures.",
    url: "/product/lego-city-fire-station",
    image: "/product/lego-city-fire-station.webp",
  },
  {
    id: "lego-star-wars-x-wing",
    name: "LEGO Star Wars X-Wing Starfighter",
    brand: "LEGO",
    price: 44.99,
    age: "9+",
    category: "building sets",
    description: "Build Luke Skywalker's iconic X-Wing Starfighter.",
    url: "/product/lego-star-wars-x-wing",
    image: "/product/lego-star-wars-x-wing.webp",
  },
  {
    id: "lego-harry-potter-hogwarts",
    name: "LEGO Harry Potter Hogwarts Castle",
    brand: "LEGO",
    price: 89.99,
    age: "9+",
    category: "building sets",
    description: "Magical Hogwarts Castle building set.",
    url: "/product/lego-harry-potter-hogwarts",
    image: "/product/lego-harry-potter-hogwarts.webp",
  },
  {
    id: "pokemon-booster-pack",
    name: "Pokémon Scarlet & Violet Booster Pack",
    brand: "Pokémon",
    price: 4.99,
    age: "6+",
    category: "trading cards",
    description: "Collect new Pokémon cards for your collection.",
    url: "/product/pokemon-booster-pack",
    image: "/product/pokemon-booster-pack.webp",
  },
  {
    id: "pokemon-elite-trainer-box",
    name: "Pokémon Elite Trainer Box",
    brand: "Pokémon",
    price: 49.99,
    age: "6+",
    category: "trading cards",
    description: "Everything you need to begin battling.",
    url: "/product/pokemon-elite-trainer-box",
    image: "/product/pokemon-elite-trainer-box.webp",
  },
  {
    id: "pokemon-pikachu-plush",
    name: "Pokémon Pikachu Plush",
    brand: "Pokémon",
    price: 19.99,
    age: "0+",
    category: "soft toys",
    description: "Soft cuddly Pikachu plush toy.",
    url: "/product/pokemon-pikachu-plush",
    image: "/product/pokemon-pikachu-plush.webp",
  },
  {
    id: "barbie-dreamhouse",
    name: "Barbie Dreamhouse",
    brand: "Barbie",
    price: 199.99,
    age: "3+",
    category: "dolls",
    description: "Large Barbie Dreamhouse with furniture.",
    url: "/product/barbie-dreamhouse",
    image: "/product/barbie-dreamhouse.webp",
  },
  {
    id: "barbie-fashion-doll",
    name: "Barbie Fashion Doll",
    brand: "Barbie",
    price: 12.99,
    age: "3+",
    category: "dolls",
    description: "Classic Barbie doll with stylish outfit.",
    url: "/product/barbie-fashion-doll",
    image: "/product/barbie-fashion-doll.webp",
  },
  {
    id: "bluey-family-home",
    name: "Bluey Family Home Playset",
    brand: "Bluey",
    price: 49.99,
    age: "3+",
    category: "playsets",
    description: "Recreate favourite Bluey adventures.",
    url: "/product/bluey-family-home",
    image: "/product/bluey-family-home.webp",
  },
  {
    id: "bluey-plush",
    name: "Bluey Plush",
    brand: "Bluey",
    price: 16.99,
    age: "0+",
    category: "soft toys",
    description: "Super soft Bluey plush toy.",
    url: "/product/bluey-plush",
    image: "/product/bluey-plush.webp",
  },
  {
    id: "paw-patrol-lookout",
    name: "Paw Patrol Lookout Tower",
    brand: "Paw Patrol",
    price: 59.99,
    age: "3+",
    category: "playsets",
    description: "Mission HQ with working lift and vehicles.",
    url: "/product/paw-patrol-lookout",
    image: "/product/paw-patrol-lookout.webp",
  },
  {
    id: "paw-patrol-chase",
    name: "Paw Patrol Chase Figure",
    brand: "Paw Patrol",
    price: 9.99,
    age: "3+",
    category: "figures",
    description: "Chase action figure with rescue vehicle.",
    url: "/product/paw-patrol-chase",
    image: "/product/paw-patrol-chase.webp",
  },
  {
    id: "nerf-elite-disruptor",
    name: "Nerf Elite Disruptor",
    brand: "NERF",
    price: 24.99,
    age: "8+",
    category: "blasters",
    description: "Foam dart blaster with rotating drum.",
    url: "/product/nerf-elite-disruptor",
    image: "/product/nerf-elite-disruptor.webp",
  },
  {
    id: "nerf-darts-pack",
    name: "NERF Elite Dart Refill Pack",
    brand: "NERF",
    price: 8.99,
    age: "8+",
    category: "accessories",
    description: "Extra foam darts for NERF blasters.",
    url: "/product/nerf-darts-pack",
    image: "/product/nerf-darts-pack.webp",
  },
  {
    id: "disney-stitch-plush",
    name: "Disney Stitch Plush",
    brand: "Disney",
    price: 18.99,
    age: "0+",
    category: "soft toys",
    description: "Cute and cuddly Stitch plush.",
    url: "/product/disney-stitch-plush",
    image: "/product/disney-stitch-plush.webp",
  },
  {
    id: "disney-frozen-elsa-doll",
    name: "Disney Frozen Elsa Doll",
    brand: "Disney",
    price: 24.99,
    age: "3+",
    category: "dolls",
    description: "Beautiful Elsa doll inspired by Frozen.",
    url: "/product/disney-frozen-elsa-doll",
    image: "/product/disney-frozen-elsa-doll.webp",
  },
  {
    id: "marvel-spiderman-figure",
    name: "Marvel Spider-Man Action Figure",
    brand: "Marvel",
    price: 14.99,
    age: "4+",
    category: "action figures",
    description: "Spider-Man poseable action figure.",
    url: "/product/marvel-spiderman-figure",
    image: "/product/marvel-spiderman-figure.webp",
  },
  {
    id: "marvel-avengers-set",
    name: "Marvel Avengers Figure Pack",
    brand: "Marvel",
    price: 29.99,
    age: "4+",
    category: "action figures",
    description: "Pack of Avengers heroes.",
    url: "/product/marvel-avengers-set",
    image: "/product/marvel-avengers-set.webp",
  },
  {
    id: "hot-wheels-20-pack",
    name: "Hot Wheels 20 Car Pack",
    brand: "Hot Wheels",
    price: 24.99,
    age: "3+",
    category: "cars",
    description: "Twenty die-cast Hot Wheels vehicles.",
    url: "/product/hot-wheels-20-pack",
    image: "/product/hot-wheels-20-pack.webp",
  },
  {
    id: "monster-jam-grave-digger",
    name: "Monster Jam Grave Digger",
    brand: "Monster Jam",
    price: 14.99,
    age: "3+",
    category: "vehicles",
    description: "Official Grave Digger monster truck.",
    url: "/product/monster-jam-grave-digger",
    image: "/product/monster-jam-grave-digger.webp",
  },
  {
    id: "play-doh-super-pack",
    name: "Play-Doh Super Colour Pack",
    brand: "Play-Doh",
    price: 14.99,
    age: "2+",
    category: "arts & crafts",
    description: "Twenty colourful tubs of Play-Doh.",
    url: "/product/play-doh-super-pack",
    image: "/product/play-doh-super-pack.webp",
  },
  {
    id: "crayola-art-case",
    name: "Crayola Inspiration Art Case",
    brand: "Crayola",
    price: 29.99,
    age: "5+",
    category: "arts & crafts",
    description: "Large art case packed with creative supplies.",
    url: "/product/crayola-art-case",
    image: "/product/crayola-art-case.webp",
  },
  {
    id: "squishmallows-12-inch",
    name: "Squishmallows 12 Inch Plush",
    brand: "Squishmallows",
    price: 19.99,
    age: "0+",
    category: "soft toys",
    description: "Ultra soft Squishmallows plush.",
    url: "/product/squishmallows-12-inch",
    image: "/product/squishmallows-12-inch.webp",
  },
  {
    id: "funko-pop-batman",
    name: "Funko Pop! Batman",
    brand: "Funko",
    price: 12.99,
    age: "3+",
    category: "collectibles",
    description: "Batman vinyl collectible figure.",
    url: "/product/funko-pop-batman",
    image: "/product/funko-pop-batman.webp",
  },
  {
    id: "funko-pop-groot",
    name: "Funko Pop! Groot",
    brand: "Funko",
    price: 12.99,
    age: "3+",
    category: "collectibles",
    description: "Marvel Groot vinyl figure.",
    url: "/product/funko-pop-groot",
    image: "/product/funko-pop-groot.webp",
  },
  {
    id: "vtech-first-steps-baby-walker",
    name: "VTech First Steps Baby Walker",
    brand: "VTech",
    price: 39.99,
    age: "6 months+",
    category: "baby toys",
    description: "Interactive walker with lights and sounds.",
    url: "/product/vtech-first-steps-baby-walker",
    image: "/product/vtech-first-steps-baby-walker.webp",
  },
  {
    id: "leapfrog-learning-friends",
    name: "LeapFrog Learning Friends Book",
    brand: "LeapFrog",
    price: 16.99,
    age: "18 months+",
    category: "learning toys",
    description: "Interactive educational story book.",
    url: "/product/leapfrog-learning-friends",
    image: "/product/leapfrog-learning-friends.webp",
  },
  {
    id: "uno-card-game",
    name: "UNO Card Game",
    brand: "Mattel Games",
    price: 7.99,
    age: "7+",
    category: "board games",
    description: "Classic family card game.",
    url: "/product/uno-card-game",
    image: "/product/uno-card-game.webp",
  },
  {
    id: "monopoly-classic",
    name: "Monopoly Classic",
    brand: "Hasbro",
    price: 24.99,
    age: "8+",
    category: "board games",
    description: "Buy, sell and trade properties.",
    url: "/product/monopoly-classic",
    image: "/product/monopoly-classic.webp",
  },
  {
    id: "dobble-card-game",
    name: "Dobble",
    brand: "Asmodee",
    price: 12.99,
    age: "6+",
    category: "board games",
    description: "Fast-paced matching card game.",
    url: "/product/dobble-card-game",
    image: "/product/dobble-card-game.webp",
  },
    {
    id: "lego-city-airport",
    name: "LEGO City Airport",
    brand: "LEGO",
    price: 79.99,
    age: "7+",
    category: "building sets",
    description: "Build a busy airport complete with passenger plane and terminal.",
    url: "/product/lego-city-airport",
    image: "/product/lego-city-airport.webp",
  },
  {
    id: "lego-city-train",
    name: "LEGO City Express Passenger Train",
    brand: "LEGO",
    price: 129.99,
    age: "7+",
    category: "building sets",
    description: "Motorised passenger train with remote control.",
    url: "/product/lego-city-train",
    image: "/product/lego-city-train.webp",
  },
  {
    id: "lego-technic-bugatti",
    name: "LEGO Technic Bugatti Bolide",
    brand: "LEGO",
    price: 44.99,
    age: "9+",
    category: "building sets",
    description: "Detailed Bugatti supercar model to build.",
    url: "/product/lego-technic-bugatti",
    image: "/product/lego-technic-bugatti.webp",
  },
  {
    id: "lego-technic-lamborghini",
    name: "LEGO Technic Lamborghini Huracán",
    brand: "LEGO",
    price: 49.99,
    age: "9+",
    category: "building sets",
    description: "Authentic Lamborghini building experience.",
    url: "/product/lego-technic-lamborghini",
    image: "/product/lego-technic-lamborghini.webp",
  },
  {
    id: "lego-speed-champions-ferrari",
    name: "LEGO Speed Champions Ferrari F40",
    brand: "LEGO",
    price: 22.99,
    age: "9+",
    category: "building sets",
    description: "Build the iconic Ferrari F40 sports car.",
    url: "/product/lego-speed-champions-ferrari",
    image: "/product/lego-speed-champions-ferrari.webp",
  },
  {
    id: "lego-speed-champions-mclaren",
    name: "LEGO Speed Champions McLaren Formula 1",
    brand: "LEGO",
    price: 24.99,
    age: "9+",
    category: "building sets",
    description: "McLaren Formula 1 race car building set.",
    url: "/product/lego-speed-champions-mclaren",
    image: "/product/lego-speed-champions-mclaren.webp",
  },
  {
    id: "lego-minecraft-fox-house",
    name: "LEGO Minecraft The Fox Lodge",
    brand: "LEGO",
    price: 17.99,
    age: "8+",
    category: "building sets",
    description: "Minecraft-inspired fox house adventure.",
    url: "/product/lego-minecraft-fox-house",
    image: "/product/lego-minecraft-fox-house.webp",
  },
  {
    id: "lego-minecraft-creeper",
    name: "LEGO Minecraft Creeper Mine",
    brand: "LEGO",
    price: 39.99,
    age: "8+",
    category: "building sets",
    description: "Mining adventure with Creepers and TNT.",
    url: "/product/lego-minecraft-creeper",
    image: "/product/lego-minecraft-creeper.webp",
  },
  {
    id: "lego-marvel-spider-man",
    name: "LEGO Marvel Spider-Man Final Battle",
    brand: "LEGO",
    price: 54.99,
    age: "10+",
    category: "building sets",
    description: "Spider-Man vs villains action playset.",
    url: "/product/lego-marvel-spider-man",
    image: "/product/lego-marvel-spider-man.webp",
  },
  {
    id: "lego-avengers-tower",
    name: "LEGO Marvel Avengers Tower",
    brand: "LEGO",
    price: 99.99,
    age: "10+",
    category: "building sets",
    description: "Epic Avengers headquarters playset.",
    url: "/product/lego-avengers-tower",
    image: "/product/lego-avengers-tower.webp",
  },
  {
    id: "lego-disney-castle",
    name: "LEGO Disney Princess Castle",
    brand: "LEGO",
    price: 84.99,
    age: "6+",
    category: "building sets",
    description: "Magical Disney castle with princess characters.",
    url: "/product/lego-disney-castle",
    image: "/product/lego-disney-castle.webp",
  },
  {
    id: "lego-friends-treehouse",
    name: "LEGO Friends Treehouse",
    brand: "LEGO",
    price: 49.99,
    age: "6+",
    category: "building sets",
    description: "Creative treehouse packed with accessories.",
    url: "/product/lego-friends-treehouse",
    image: "/product/lego-friends-treehouse.webp",
  },
  {
    id: "star-wars-darth-vader",
    name: "Star Wars Darth Vader Action Figure",
    brand: "Star Wars",
    price: 24.99,
    age: "4+",
    category: "action figures",
    description: "Poseable Darth Vader action figure.",
    url: "/product/star-wars-darth-vader",
    image: "/product/star-wars-darth-vader.webp",
  },
  {
    id: "star-wars-grogu-plush",
    name: "Star Wars Grogu Plush",
    brand: "Star Wars",
    price: 18.99,
    age: "0+",
    category: "soft toys",
    description: "Soft Grogu (Baby Yoda) plush.",
    url: "/product/star-wars-grogu-plush",
    image: "/product/star-wars-grogu-plush.webp",
  },
  {
    id: "star-wars-lightsaber",
    name: "Star Wars Electronic Lightsaber",
    brand: "Star Wars",
    price: 34.99,
    age: "5+",
    category: "role play",
    description: "Light-up electronic lightsaber with sound effects.",
    url: "/product/star-wars-lightsaber",
    image: "/product/star-wars-lightsaber.webp",
  },
  {
    id: "star-wars-millennium-falcon",
    name: "Star Wars Millennium Falcon",
    brand: "Star Wars",
    price: 59.99,
    age: "4+",
    category: "vehicles",
    description: "Millennium Falcon vehicle with figures.",
    url: "/product/star-wars-millennium-falcon",
    image: "/product/star-wars-millennium-falcon.webp",
  },
  {
    id: "nee-doh-nice-cube",
    name: "NeeDoh Nice Cube",
    brand: "Schylling",
    price: 5.99,
    age: "3+",
    category: "sensory toys",
    description: "Super satisfying squishy sensory cube.",
    url: "/product/nee-doh-nice-cube",
    image: "/product/nee-doh-nice-cube.webp",
  },
  {
    id: "nee-doh-dream-drop",
    name: "NeeDoh Dream Drop",
    brand: "Schylling",
    price: 4.99,
    age: "3+",
    category: "sensory toys",
    description: "Colourful stress and sensory fidget toy.",
    url: "/product/nee-doh-dream-drop",
    image: "/product/nee-doh-dream-drop.webp",
  },
  {
    id: "nee-doh-groovy-fruit",
    name: "NeeDoh Groovy Fruit",
    brand: "Schylling",
    price: 6.99,
    age: "3+",
    category: "sensory toys",
    description: "Squishy fruit-shaped sensory toys.",
    url: "/product/nee-doh-groovy-fruit",
    image: "/product/nee-doh-groovy-fruit.webp",
  },
  {
    id: "nee-doh-gummy-bear",
    name: "NeeDoh Gummy Bear",
    brand: "Schylling",
    price: 5.99,
    age: "3+",
    category: "sensory toys",
    description: "Large squishy gummy bear fidget toy.",
    url: "/product/nee-doh-gummy-bear",
    image: "/product/nee-doh-gummy-bear.webp",
  },
  {
    id: "magic-mixies-cauldron",
    name: "Magic Mixies Magical Cauldron",
    brand: "Magic Mixies",
    price: 69.99,
    age: "5+",
    category: "interactive toys",
    description: "Create your own magical pet with spells.",
    url: "/product/magic-mixies-cauldron",
    image: "/product/magic-mixies-cauldron.webp",
  },
  {
    id: "bitzee-digital-pet",
    name: "Bitzee Interactive Digital Pet",
    brand: "Bitzee",
    price: 34.99,
    age: "5+",
    category: "interactive toys",
    description: "Virtual pet that reacts to touch and movement.",
    url: "/product/bitzee-digital-pet",
    image: "/product/bitzee-digital-pet.webp",
  },
  {
    id: "tech-deck-skate-pack",
    name: "Tech Deck Finger Skateboard Pack",
    brand: "Tech Deck",
    price: 9.99,
    age: "6+",
    category: "collectibles",
    description: "Authentic finger skateboards with real graphics.",
    url: "/product/tech-deck-skate-pack",
    image: "/product/tech-deck-skate-pack.webp",
  },
  {
    id: "kinetic-sand-playset",
    name: "Kinetic Sand Sandbox Playset",
    brand: "Kinetic Sand",
    price: 19.99,
    age: "3+",
    category: "arts & crafts",
    description: "Mould and shape magical flowing sand.",
    url: "/product/kinetic-sand-playset",
    image: "/product/kinetic-sand-playset.webp",
  },
  {
    id: "hexbug-nano-starter-set",
    name: "HEXBUG Nano Starter Set",
    brand: "HEXBUG",
    price: 24.99,
    age: "5+",
    category: "robots",
    description: "Create mazes for robotic Nano bugs.",
    url: "/product/hexbug-nano-starter-set",
    image: "/product/hexbug-nano-starter-set.webp",
  },
  {
    id: "rubiks-cube-3x3",
    name: "Rubik's Cube 3x3",
    brand: "Rubik's",
    price: 11.99,
    age: "8+",
    category: "puzzles",
    description: "The classic 3x3 Rubik's Cube puzzle.",
    url: "/product/rubiks-cube-3x3",
    image: "/product/rubiks-cube-3x3.webp",
  },
  {
    id: "magnatiles-classic",
    name: "Magna-Tiles Classic Set",
    brand: "Magna-Tiles",
    price: 44.99,
    age: "3+",
    category: "construction toys",
    description: "Magnetic building tiles for creative play.",
    url: "/product/magnatiles-classic",
    image: "/product/magnatiles-classic.webp",
  },
  {
    id: "brainstorm-projector",
    name: "Brainstorm Star Projector",
    brand: "Brainstorm",
    price: 29.99,
    age: "6+",
    category: "science toys",
    description: "Project stars and constellations onto your ceiling.",
    url: "/product/brainstorm-projector",
    image: "/product/brainstorm-projector.webp",
  },
  {
    id: "national-geographic-volcano-kit",
    name: "National Geographic Volcano Science Kit",
    brand: "National Geographic",
    price: 22.99,
    age: "8+",
    category: "science toys",
    description: "Build and erupt your own volcano experiment.",
    url: "/product/national-geographic-volcano-kit",
    image: "/product/national-geographic-volcano-kit.webp",
  },
  {
    id: "fuggler-funny-ugly-monster",
    name: "Fuggler Funny Ugly Monster",
    brand: "Fuggler",
    price: 9.99,
    age: "4+",
    category: "collectibles",
    description: "Quirky monster plush with human-like teeth.",
    url: "/product/fuggler-funny-ugly-monster",
    image: "/product/fuggler-funny-ugly-monster.webp",
  },
  {
  id: "classic-teddy-bear-brown",
  name: "Classic Brown Teddy Bear",
  brand: "Snuggle Buddies",
  price: 14.99,
  age: "0+",
  category: "soft toys",
  description: "A super soft traditional teddy bear with cuddly brown fur.",
  url: "/product/classic-teddy-bear-brown",
  image: "/product/classic-teddy-bear-brown.webp",
},
{
  id: "jumbo-teddy-bear",
  name: "Jumbo Teddy Bear",
  brand: "Snuggle Buddies",
  price: 39.99,
  age: "0+",
  category: "soft toys",
  description: "Extra large teddy bear perfect for hugs and bedtime cuddles.",
  url: "/product/jumbo-teddy-bear",
  image: "/product/jumbo-teddy-bear.webp",
},
{
  id: "cream-teddy-bear",
  name: "Cream Teddy Bear",
  brand: "Snuggle Buddies",
  price: 19.99,
  age: "0+",
  category: "soft toys",
  description: "Soft cream teddy bear with a ribbon bow and fluffy fur.",
  url: "/product/cream-teddy-bear",
  image: "/product/cream-teddy-bear.webp",
},
{
  id: "paddington-bear-plush",
  name: "Paddington Bear Plush",
  brand: "Paddington",
  price: 24.99,
  age: "0+",
  category: "soft toys",
  description: "Official Paddington teddy bear wearing his famous blue coat and red hat.",
  url: "/product/paddington-bear-plush",
  image: "/product/paddington-bear-plush.webp",
},
{
  id: "bedtime-teddy-bear",
  name: "Bedtime Teddy Bear",
  brand: "Little Dreams",
  price: 17.99,
  age: "0+",
  category: "soft toys",
  description: "A cuddly bedtime teddy bear made from extra soft plush fabric.",
  url: "/product/bedtime-teddy-bear",
  image: "/product/bedtime-teddy-bear.webp",
},
{
  id: "rainbow-teddy-bear",
  name: "Rainbow Teddy Bear",
  brand: "Happy Hugs",
  price: 21.99,
  age: "0+",
  category: "soft toys",
  description: "Colourful rainbow teddy bear with embroidered paws.",
  url: "/product/rainbow-teddy-bear",
  image: "/product/rainbow-teddy-bear.webp",
},
];